apiVersion: v1
kind: Service
metadata:
  name: multigo-app
  labels: 
    app: go-app
spec:
  selector:
    app: go-app
  type: NodePort
  ports:
    - port: 8081
      nodePort: 30008
      targetPort: 8081


